config/routes.rb
Rails.application.routes.draw do
  
  get 'paginas_estaticas/pagina_construccion'

  get '/ayuda', to:'paginas_estaticas#pagina_construccion'

  resources :tweets
  resources :monstruos
  resources :victimas
  
  root 'tweets#default'

end

app/models/monstruo.rb
class Monstruo < ActiveRecord::Base
  has_many :tweets, dependent: :destroy
  has_many :victimas
  default_scope -> { order :nombre }
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :monstruo

  def cstar
	m=Monstruo.find(params[:monstruo_id])
        if m.count > 2
		m.critter_star = true
	end
  end
end

app/models/victima.rb
class Victima < ActiveRecord::Base
belongs_to :monstruo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/monstruos_controller.rb
class MonstruosController < ApplicationController
  before_action :get, only: [:show, :destroy]
  before_action :comp, only: [:show]
  def index 
  end
  def get
      @monstruo=Monstruo.find(params[:id])
  end
  def comp
	if @monstruo.tweets.count < 2
		flash[:notice]= "No tiene tweets"
		redirect_to(monstruos_path)
        end   
  end
  def show
	
  end

  def edit
    
  end
  
  def destroy
	@monstruo.destroy
        redirect_to(monstruos_path)
  end
end

app/controllers/paginas_estaticas_controller.rb
class PaginasEstaticasController < ApplicationController
  def pagina_construccion
  end
end

app/controllers/tweets_controller.rb
# encoding = utf-8
class TweetsController < ApplicationController
  
  def new
  	@tweet = Tweet.new
  end

  def default    
  end
  
  def index
  end

  def show
  end
  def create
	@tweet = Tweet.create(params.require(:tweet).permit([:estado, :nombre]))
  end
end

app/controllers/victimas_controller.rb
class VictimasController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monstruos_helper.rb
module MonstruosHelper
end

app/helpers/paginas_estaticas_helper.rb
module PaginasEstaticasHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/victimas_helper.rb
module VictimasHelper
end

app/views/layouts/_header.html.erb
<header>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          
          
          <%= link_to root_path, class: 'navbar-brand' do %>
            <%= image_tag "logo.png", title: "Logo", class: "logo" %>
            Critter
          <% end %>
        </div>
        <div class="collapse navbar-collapse">
          
        </div><!--/.nav-collapse -->
      </div>

    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Critter </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container"> 
<% if flash[:notice] %>
	<div class="alert alert-danger">
		<%= flash[:notice] %>
        </div>
        <% end %>
	<%= yield %>
</div>

</body>
</html>

app/views/monstruos/edit.html.erb
<h1> Editar monstruo </h1>

<p> No está hecho </p>

app/views/monstruos/index.html.erb
<h1> Listado de Monstruos </h1>

<table class="table">

	<tr>
		<th> Nombre </th>
		<th> Descripción </th>
		<th> Critter star </th>
		<th> Acciones </th>
	</tr>

	<% monstruos = Monstruo.all %>
	<% monstruos.each do |monstruo| %>
		<tr>
			<td> <%= link_to monstruo.nombre, monstruo %> </td>
			<td> <%= monstruo.descripcion %> </td>
			<td> <%= (monstruo.critter_star) ? 'Si' : 'No' %> </td>
			<td>
				<%= link_to "Editar", edit_monstruo_path(monstruo), class: 'btn btn-info btn-sm' %>
				<%= link_to "Eliminar", monstruo, method: :delete, class: 'btn btn-danger btn-sm', data: {confirm:"Esta seguro?"} %>
			</td>
		</tr>
	<% end %>

	<% if monstruos.size == 0 %>
		<tr> <td colspan="3"> No hay monstruos </td> </tr>
	<% end %>

</table>

app/views/monstruos/show.html.erb
<h1><%= @monstruo.nombre %></h1>
<p> Descripcion: <%= @monstruo.descripcion %></p>
<ul>Tweets: <% @monstruo.tweets.each do |t| %>
<li><%= t.estado %></li>
<% end %>
</ul>

app/views/monstruos/ver.html.erb
<!------------------------------------------------------ 
Debe mostrarse la información del primer monstruo sin
usar el id.
Se debe mostrar el nombre (como título) y la descripción 
(como párrafo).
------------------------------------------------------>

HACER <br>
/app/views/monstruos/ver.html.erb

app/views/paginas_estaticas/pagina_construccion.html.erb
<img src="/img/o.png">

app/views/tweets/default.html.erb
<h1> Bienvenido a Critter </h1>
<h3> ¿Qué desea hacer? </h3>
<ul>
  <li> <%= link_to "Nuevo Tweet", new_tweet_path %></li>
  <li> <%= link_to "Listado de Monstruos", monstruos_path %></li>
  <li> <%= link_to "Listado de Victimas", victimas_path %></li>  
</ul>

<p><%= link_to "Ayuda", ayuda_path %></p>

app/views/tweets/index.html.erb
<!-- Listado de tweets -->

app/views/tweets/new.html.erb
<div class="container">
	<h1> Crear un tweet para un monstruo </h1>

	<%= form_for @tweet do |f| %>
		
		<div class="row">
			<div class="col-md-4">
				<%= f.label :monstruo_id, 'Monstruo' %>
  				<%= collection_select(:tweet, :monstruo_id, Monstruo.all, :id, :nombre, {}, { class: 'form-control'}) %>
  			</div>
  		</div>


		<div class="row">
			<div class="col-md-6">
				<%= f.label :estado %>
  				<%= f.text_area :estado, class: 'form-control', label: 'Estado', placeholder: 'Ingrese el estado' %>
  			</div>
  		</div>

  		<%= f.submit "Crear tweet", class: 'btn btn-primary' %>
  	</div>
<% end %>
</div>

app/views/tweets/show.html.erb
<!-- Ver un tweet -->

app/views/victimas/index.html.erb
<h1>Victimas</h1>
<ul>
<% Victima.all.each do |v| %>
<li><p><%= v.nombre %> asesinado por <%= v.monstruo.nombre %></p></li>
<% end %>
</ul>